// extraReducers = indicates are additional reducers apart from the reducers generated by create slice 
import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    imageArr: [],
    imageStatusArr: []
}

const AddPhotoSlice = createSlice({
    name: 'AddPhoto',
    initialState,
    reducers: {
        updateAddPhotoValues: (state, action) => {
            state[action.payload.key] = action.payload.value
            return state;
        },
        updateMultipleAddPhotoValues: (state, action) => {
            state = { ...state, ...action.payload }
            return state;
        },
        resetAddPhoto: (state, action) => {
            state.imageArr = [];
            state.imageStatusArr = [];
        }
    }
})


export default AddPhotoSlice.reducer
export const { updateAddPhotoValues, updateMultipleAddPhotoValues, resetAddPhoto } = AddPhotoSlice.actions