// extraReducers = indicates are additional reducers apart from the reducers generated by create slice 
import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    pincode: '',
    block_num: '',
    street: '',
    landmark: '',
    area: '',
    city: '',
    state: ''
}

const AddressSlice = createSlice({
    name: 'Address',
    initialState,
    reducers: {
        updateAddressAction: (state, action) => {
            state[action.payload.key] = action.payload.value
        },
        updateMultipleAddressValues: (state, action) => {
            state = { ...state, ...action.payload };
            return state;
          },
    }
})


export default AddressSlice.reducer
export const { updateAddressAction, updateMultipleAddressValues } = AddressSlice.actions
