// extraReducers = indicates are additional reducers apart from the reducers generated by create slice 
import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    timmingArr: [],
}

const AddTiimmingSlice = createSlice({
    name: 'TimmingArr',
    initialState,
    reducers: {
        updateTimmingArr: (state, action) => {
            state = { ...state, ...action.payload };
            return state;
        },
        resetAddTiming: (state, action) => {
            state.timmingArr = []

        },
        set24hr: (state, action) => {
            let temp24TimeArr = state.timmingArr[0];
            temp24TimeArr.selectedWeekValArr = new Array(7).fill(true);
            temp24TimeArr.openAtVal = "Open 24hrs";
            temp24TimeArr.timeSlotArrData = [temp24TimeArr];
            state.timmingArr = [temp24TimeArr];
            return state
        }
    }
})


export default AddTiimmingSlice.reducer
export const { updateTimmingArr, resetAddTiming, set24hr } = AddTiimmingSlice.actions