// extraReducers = indicates are additional reducers apart from the reducers generated by create slice 
import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    bussinessList: [],
}

const BussinessDataSlice = createSlice({
    name: 'BussinessList',
    initialState,
    reducers: {
        updateBussinessList: (state, action) => {
            state[action.payload.key] = action.payload.value
        }
    }
})


export default BussinessDataSlice.reducer
export const { updateBussinessList } = BussinessDataSlice.actions