// extraReducers = indicates are additional reducers apart from the reducers generated by create slice 
import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    historyState: [],   
    currentHistoryIndex: 0, 
    selectedCategories: []                                    
}
/*-------------------------------
historyState: [
    {
        categoroyList: []
        selectedCatIDs: [ncadids]- [12414214,4314123,43242342,53245234.]
    }
]
-------------------------------*/


const CategorySlice = createSlice({
    name: 'category',
    initialState,
    reducers: {
        updateCategoryData: (state, action) => {
            state = { ...state, ...action.payload };
            return state;
        },
        resetCategoryToDefault: (state, action) => {
            historyState = []
            currentHistoryIndex = 0
            selectedCategories = []  
        }
    }
})


export default CategorySlice.reducer
export const { updateCategoryData, resetCategoryToDefault } = CategorySlice.actions