// extraReducers = indicates are additional reducers apart from the reducers generated by create slice
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  currentComponent: "sign_up",
};

const CurrentComponentSlice = createSlice({
  name: "currentComponent",
  initialState,
  reducers: {
    currentPage: (state, action) => {
      state.currentComponent = action.payload;
    },
  },
});

export default CurrentComponentSlice.reducer;
export const { currentPage } = CurrentComponentSlice.actions;

// currentComponent/currentPage = Actions type
