// extraReducers = indicates are additional reducers apart from the reducers generated by create slice
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    isShowOTP: false,
    moblieNumber: '',
};

const landinfPageSlice = createSlice({
  name: "landinfPageSlice",
  initialState,
  reducers: {
    updateOTPValues: (state, action) => {
      state[action.payload.key] = action.payload.value;
    },
    updateMultipleOTPValues: (state, action) => {
      state = { ...state, ...action.payload };
      return state;
    },
  },
});

export default landinfPageSlice.reducer;
export const { updateOTPValues, updateMultipleOTPValues } =
landinfPageSlice.actions;
