export const DesignationList = [
    "Assistant Manager",
    "Assistant Marketing Manager",
    "CEO (Chief Executive Officer)",
    "Chairman",
    "Chairman & CEO",
    "Chairman & MD",
    "COO (Chief Operating Officer)",
    "Digital Marketing Manager",
    "Director",
    "Founder",
    "General Manager",
    "Head Sales & Marketing",
    "Manager",
    "Managing Director (MD)",
    "Marketing Head",
    "Marketing Manager",
    "Owner",
    "Partner",
    "President",
    "Proprietor",
    "Sales Executive",
    "Sales Manager",
    "Vice President",
    "Other"
]